backend:   
  name: git-gateway
  repo: oscc
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "static/images" # Media files will be stored in the repo under static/images
public_folder: "/images" # The src attribute for uploaded media will begin with /images
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}-{{year}}-{{month}}-{{day}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Job Title", name: "jobtitle", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Body", name: "body", widget: "markdown"}
